# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='aadhar_no',
            field=models.IntegerField(blank=True, default=None, verbose_name='Aadhar No.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='acertificate',
            field=models.FileField(default=None, upload_to='aadhar', verbose_name='Upload Aadhar Card '),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=500, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bcertificate',
            field=models.FileField(default=None, upload_to='blind', verbose_name='Upload Blind Identity Certificate'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(default=None, null=True, verbose_name='Work Experience'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='----', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(blank=True, default=None, verbose_name='Mobile No.'),
        ),
    ]
