# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180615_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Mobile No.'),
        ),
    ]
